version: '3.8'

services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - 3000:8080

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-nginx
  #   container_name: nest_nginx
  #   depends_on:
  #     - nest
  #   environment:
  #     - NGINX_SERVER_NAME=localhost
  #     - NGINX_HOST=nest
  #     - NEST_PORT=3000
  #     - NGINX_MAX_BODY=100M
  #   ports:
  #     - 80:80
